config/routes.rb
Mlug::Application.routes.draw do
  get "welcome/index"
  get "welcome/about"

  resources :posts do
    member do
      post '', to: 'posts#replay', as: :replay
    end
    resources :comments, :except => [ :index, :new, :create ] do
      member do
        post '', to: "comments#replay", as: :replay
      end
    end
  end

  devise_for :users, :controllers => { :passwords => "users/passwords" }
  
  # Private
  namespace :users, :as => "" do
    resource :profile, :only => [ :show, :update ]
  end
  
  # Public
  resources :users, :only => [] do
    get :profile
  end
  
  root :to => 'welcome#index'

  match 'about' => 'welcome#about'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    alias_action :delete, :to => :destroy
    user ||= User.new
    if user.admin?
      can :manage, :all
    end
    if user.moderator?
      can :update, [ Post, Comment ]
    end
    if user.not_banned?
      can [ :create, :replay, :preview ], [ Post, Comment ] if user.not_guest?
      can [ :update, :destroy ], Post, :user_id => user.id
    end

    can :read, :all
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :author,
    :class_name => "User",
    :foreign_key => "user_id"
  belongs_to :parent,
    class_name: 'Comment'
  belongs_to :post
  attr_accessible :text
  validates :text,   presence: true
  validates :author, presence: true
  validates :post,   presence: true

  def answers
    post.comments.select { |c| c.parent == self }
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :body, :title
  belongs_to :author,
    :class_name => "User",
    :foreign_key => "user_id"
  has_many :comments
  validates :author, :presence => true
  validates :title, :presence => true
  validates :body, :presence => true

  def answers
    comments.select { |c| c.parent.nil? }
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
 
  attr_accessible :nickname,
    :jabber,
    :city,
    :distributions,
    :interests

  has_many :posts
  has_many :comments

  ROLES = %w[ banned moderator admin ]

  def roles=(roles)
    self.roles_mask = (roles & ROLES).map { |r| 2**ROLES.index(r) }.inject(0, :+)
  end

  def roles
    ROLES.reject do |r|
      ((roles_mask || 0) & 2**ROLES.index(r)).zero?
    end
  end

  def admin?
    has_role? :admin
  end

  def moderator?
    has_role? :moderator
  end

  def guest?
    id.nil?
  end

  def not_guest?
    not guest?
  end

  def banned?
    has_role? :banned
  end

  def not_banned?
    not banned?
  end

  def has_role?(role)
    roles.include?(role.to_s)
  end

  def is?(role)
    has_role?(role)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  rescue_from CanCan::AccessDenied do |exception|
    flash[:alert] = I18n.t('access_denied')
    redirect_to root_url
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate_user!, :except => [ :show ]
  load_and_authorize_resource :post
  load_and_authorize_resource :comment, :through => :post
  helper_method :comments_for
  helper_method :wrap_comments

  def show
    @new_comment = @post.comments.build
  end

  def preview
  end

  def replay
    @new_comment = @post.comments.build(params[:comment])
    @new_comment.author = current_user
    @new_comment.parent = @comment
    if params[:preview]
      render :show
    elsif @new_comment.save
      redirect_to post_url(@post.id)
    else
      render :show, :alert => 'failed to replay'
    end
  end

  def edit
  end

  def update
    if @comment.update_attributes(params[:comment])
#      flash[:notice] = I18n.t('')
      redirect_to post_url(@comment.post_id)
    else
      render :edit
    end
  end

  def destroy
    @comment.destroy
#    notice[:flash] = I18n.t('')
    redirect_to post_url(@comment.post_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!, :except => [ :index, :show ]
  load_and_authorize_resource
  
  def new
  end
  
  def replay
    @comment = @post.comments.build(params[:comment])
    @comment.author = current_user
    if params[:preview]
      render :show
    elsif @comment.save
      redirect_to post_url(@post.id, :anchor => "comment_#{@comment.id}")
    else
      render :show
    end
  end

  def create
    @post.author = current_user
    if params[:preview]
      render :new
    elsif @post.save
      redirect_to @post, :notice => "created"
    else
      render :new, :notice => "Something went wrong"
    end
  end
  
  def show
  end
  
  def edit
  end
  
  def update
    if @post.update_attributes(params[:post])
      redirect_to post_path(@post)
    else
      render :edit
    end
  end
  
  def destroy
    @post.destroy
    #flash[:notice] = I18n.t('')
    redirect_to root_url
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  skip_before_filter :require_no_authentication, :only => :new
end

app/controllers/users/profiles_controller.rb
class Users::ProfilesController < ApplicationController
  before_filter :authenticate_user!
  
  def show
  end
  
  def update
    if current_user.update_attributes(params[:user])
      flash.now[:notice] = "updated"
    else
      flash.now[:alert] = "error"
    end
    render :show
  end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def profile
    @user = User.find(params[:user_id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @posts = Post.all
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def present(object, klass = nil)
    klass ||= "#{object.class}Presenter".constantize
    presenter = klass.new(object, self)
    yield presenter if block_given?
    presenter
  end

  def devise_registration_error_messages!(template_name)
    return "" if resource.errors.empty?
    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("devise.registrations.errors.messages.#{template_name}.not_saved",
                      :count => resource.errors.count,
                        :resource => resource.class.model_name.human.downcase)

                      html = <<-HTML
<div id="error_explanation">
<h2>#{sentence}</h2>
<ul>#{messages}</ul>
</div>
                      HTML

                      html.html_safe
  end

  def info_messages
    puts flash[:error]
    if flash[:error]
      flash[:error].to_s
    end
    if notice
      notice
    end
    if alert
      alert
    end
  end

=begin
  def redcarpet_markdown(text)
    render = Redcarpet::Render::HTML.new({
      filter_html: true,
      no_styles: true,
      hard_wrap: true
    })
    markdown = Redcarpet::Markdown.new(render, {
      no_intra_emphasis: true,
      fenced_code_blocks: true
    })
    markdown.render(ERB::Util.html_escape(text)).html_safe
  end
=end

  def showdown_markdown(text, cut)
    c = V8::Context.new
    #showdown = File.read(Rails.root.join('vendor/assets/javascripts/showdown.js'))
    markdown = File.read(Rails.root.join('vendor/assets/javascripts/markdown.js'))
    #c.eval(showdown)
    c.eval('window = {}')
    c.eval(markdown)
    #c.eval("conv = (new Showdown.converter())")
    #c[:conv].makeHtml(ERB::Util.html_escape(text)).html_safe
    c[:window].markdown.toHTML(text, "Gruber", { cut: cut }).html_safe
  end

=begin
  def syntax_highlighter(html)
    doc = Nokogiri::HTML(html)
    doc.search("//pre[@lang]").each do |pre|
      pre.replace Albino.colorize(pre.text.rstrip, pre[:lang])
    end
    doc.to_s
  end
=end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def answers_for(post_or_comment)
    render partial: 'posts/comment', collection: post_or_comment.answers
  end
end

app/helpers/users/passwords_helper.rb
module Users::PasswordsHelper
end

app/helpers/users/profiles_helper.rb
module Users::ProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.haml
- present comment do |comment_presenter|
  .comment{ id: comment_presenter.id }
    %span.author_name
      = comment_presenter.author.email
      = comment_presenter.link_to_comment
    %span.comment_text= comment_presenter.text
    %span.comment_actions
      = comment_presenter.actions
    .replays
      = yield if block_given?

app/views/comments/_replay_form.html.haml
= form_for [post, new_comment], url: replay_post_comment_path(post, comment), method: :post do |f|
  = f.text_area :text, rows: 4
  %p
    = f.submit t('replay')
    = f.submit t('preview'), name: 'preview'

app/views/comments/show.html.haml
- present @comment do |comment_presenter|
  = render layout: 'comments/comment', locals: { comment: @comment } do
    - unless @new_comment.text.blank?
      = render @new_comment
    = comment_presenter.replay_form(@new_comment)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Example
    %title MLUG.ru - Московская группа пользователей Linux
    %link{ :rel => "shortcut icon", :href => "/favicon.png", :type => "image/x-icon" }
    -#%link{ :href=>'http://fonts.googleapis.com/css?family=Jura&subset=latin,cyrillic', :rel=>'stylesheet', :type=>'text/css' }
    %link{ :href=>'http://fonts.googleapis.com/css?family=Jura&subset=latin,cyrillic', :rel=>'stylesheet', :type=>'text/css' }
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    = info_messages
    #container
      #center-column
        = render 'shared/header'
        #middle><
          = yield
        = render 'shared/footer'

app/views/layouts/comments.html.haml
!!!
%html
  %head
    %title MLUG.ru - Московская группа пользователей Linux
    %link{ :rel => "shortcut icon", :href => "/favicon.png", :type => "image/x-icon" }
    -#%link{ :href=>'http://fonts.googleapis.com/css?family=Jura&subset=latin,cyrillic', :rel=>'stylesheet', :type=>'text/css' }
    %link{ :href=>'http://fonts.googleapis.com/css?family=Jura&subset=latin,cyrillic', :rel=>'stylesheet', :type=>'text/css' }
    = stylesheet_link_tag    "application", :media => "all"
    = stylesheet_link_tag    "comments"
    = javascript_include_tag "application"
    = javascript_include_tag "comments"
    = javascript_include_tag "markdown"
    = javascript_include_tag "classes"
    = javascript_include_tag "comment-editor"
    = javascript_include_tag "underscore"
    = javascript_include_tag "markdown-toolbar"
    = yield(:styles)
    = yield(:scripts)
    = csrf_meta_tags
  %body
    = info_messages
    #container
      #center-column
        = render 'shared/header'
        #middle><
          = yield
        = render 'shared/footer'

app/views/layouts/posts.html.haml
!!!
%html
  %head
    %title MLUG.ru - Московская группа пользователей Linux
    %link{ :rel => "shortcut icon", :href => "/favicon.png", :type => "image/x-icon" }
    -#%link{ :href=>'http://fonts.googleapis.com/css?family=Jura&subset=latin,cyrillic', :rel=>'stylesheet', :type=>'text/css' }
    %link{ :href=>'http://fonts.googleapis.com/css?family=Jura&subset=latin,cyrillic', :rel=>'stylesheet', :type=>'text/css' }
    = stylesheet_link_tag    "application", :media => "all"
    = stylesheet_link_tag    "posts"
    = stylesheet_link_tag    "comments"
    -#= stylesheet_link_tag    "jquery-ui"
    = javascript_include_tag "application"
    = javascript_include_tag "posts"
    -#= javascript_include_tag "jquery-ui"
    -#= javascript_include_tag "rangy-core"
    -#= javascript_include_tag "hallo"
    = javascript_include_tag "markdown"
    -#= javascript_include_tag "to-markdown"
    -#= javascript_include_tag "editor"
    = javascript_include_tag "underscore"
    = javascript_include_tag "markdown-toolbar"
    = javascript_include_tag "classes"
    = javascript_include_tag "comment-editor"
    = javascript_include_tag "post-editor"
    = yield(:styles)
    = yield(:scripts)
    = csrf_meta_tags
  %body
    = info_messages
    #container
      #center-column
        = render 'shared/header'
        #middle><
          = yield
        = render 'shared/footer'

app/views/layouts/welcome.html.haml
!!!
%html
  %head
    %title MLUG.ru - Московская группа пользователей Linux
    %link{ :rel => "shortcut icon", :href => "/favicon.png", :type => "image/x-icon" }
    -#%link{ :href=>'http://fonts.googleapis.com/css?family=Jura&subset=latin,cyrillic', :rel=>'stylesheet', :type=>'text/css' }
    %link{ :href=>'http://fonts.googleapis.com/css?family=Jura&subset=latin,cyrillic', :rel=>'stylesheet', :type=>'text/css' }
    = stylesheet_link_tag    "application", :media => "all"
    = stylesheet_link_tag    "welcome"
    = stylesheet_link_tag    "posts"
    = javascript_include_tag "application"
    = javascript_include_tag "welcome"
    = yield(:styles)
    = yield(:scripts)
    = csrf_meta_tags
  %body
    = info_messages
    #container
      #center-column
        = render 'shared/header'
        #middle><
          = yield
        = render 'shared/footer'

app/views/posts/_comment.html.haml
= render layout: 'comments/comment', locals: { comment: comment } do
  = answers_for(comment)

app/views/posts/_post.html.haml
- present @post do |post_presenter|
  = form_for @post, class: 'post_form' do |f|
    .actions
      = post_presenter.create_link(f)
      = post_presenter.preview_link(f)
    #post_preview{ data: { 'default-text' => t('nothing_to_preview') }}
      - if params[:preview] and not @post.body.blank?
        = showdown_markdown(@post.body)
    #post_editor
      .field
        = f.label :title
        %br
        = f.text_field :title
      .field
        = f.label :body
        %br
        = f.text_area :body, id: 'source'
    .actions
      = post_presenter.create_link(f)
      = post_presenter.preview_link(f)

app/views/posts/_replay_form.html.haml
%p
  = t('posts.add_comment')
  = form_for [post, comment_presenter.comment], url: replay_post_path(post, anchor: comment_presenter.id) do |f|
    = f.text_area :text, rows: 4
    %p
      = f.submit t('replay') 
      = f.submit t('preview'), name: 'preview'

app/views/posts/edit.html.haml
Edit post
= render @post

app/views/posts/new.html.haml
New post
= render @post

app/views/posts/show.html.haml
- present @post do |post_presenter|
  %hr
    %b= post_presenter.title
  %hr
  = post_presenter.body
  = post_presenter.actions
  %hr
  #comments
    = post_presenter.comments
  - present (@comment || @post.comments.build) do |comment_presenter|
    = post_presenter.replay_form(comment_presenter)
    - if can? :replay, Comment
      %script{ type: 'text/template', id: 'comment_form_template' }
        = render partial: 'comments/replay_form', locals: { post: @post, comment: 'COMMENT', new_comment: Comment.new }
      %script{ type: 'text/template', id: 'comment_template' }
        = render partial: 'comments/comment', locals: { comment: current_user.comments.build { |c| c.post = @post }}

app/views/shared/_footer.html.haml
#footer

app/views/shared/_header.html.haml
#login
  - if current_user
    = link_to current_user.email, profile_path
    %br
    = link_to t('.sign_out'), destroy_user_session_path, :method => :delete
  - else
    = link_to t('.sign_in'), new_user_session_path, :class => "button"

#header
  %span.column.column-1
    = link_to root_path do
      %img{ :src => image_path("mlug-icon-small.png") }
  %span.column.column-2
    -#%ul#menu><
      %li.menu-item.first
        = link_to "На главную", root_path
      %li.menu-item
        = link_to "Календарь", root_path
      %li.menu-item
        = link_to "Форум", root_path
      %li.menu-item.last
        = link_to "О нас", about_path
    #header-logo-text
      = link_to "MLUG.ru", root_path, :class => "acronim"
      %br
      %span.fulltext= t('.mlug-fulltext')

app/views/users/profile.html.haml
- present @user do |user_presenter|
  %table.profile
    %tr
      %td Nickname
      %td
        = user_presenter.nickname
    %tr.line
      %td Email
      %td
        = user_presenter.email
    %tr.line
      %td Jabber
      %td
        = user_presenter.jabber
    %tr.line
      %td City
      %td
        = user_presenter.city

app/views/users/profiles/show.html.haml
= form_for current_user, :url => profile_path do |f|
  %table.profile
    %tr
      %td
        = f.label :nickname
      %td
        = f.text_field :nickname
    %tr.line
      %td
        = f.label :email
      %td
        = f.text_field :email
    %tr.line
      %td
        = f.label :jabber
      %td
        = f.text_field :jabber
    %tr.line
      %td
        = f.label :city
      %td
        = f.text_field :city
    %tr.line
      %td
        = f.label :distributions
      %td
        = f.text_field :distributions
    %tr.line
      %td
      %td
        = link_to "Сменить пароль", edit_user_registration_path
    %tr.actions
      %td
      %td
        = f.submit

app/views/welcome/_post.html.haml
- present post, PostPreviewPresenter do |post_preview_presenter|
  %article.post_preview
    .actions
      = post_preview_presenter.actions
    %h2
      = post_preview_presenter.title
    %div
      = post_preview_presenter.body
    .read_more
      = post_preview_presenter.read_more
    .info
      = post_preview_presenter.info

app/views/welcome/_post_actions.html.haml
- if can? :update, post
  = link_to edit_post_path(post), class: 'post-action', title: t('edit') do
    %i.icon-pencil
    = t('edit')
- if can? :delete, post
  = link_to post, :method => :delete, :confirm => t('are_you_sure'), title: t('delete') do
    %i.icon-trash
    = t('delete')

app/views/welcome/_post_info.html.haml
%span
  %i.icon-comments-alt
  = post.comments.count
|
%span
  = link_to post.author.email, user_profile_path(post.author)

app/views/welcome/about.html.haml
%h1 Welcome#about
%p Find me in app/views/welcome/about.html.erb

app/views/welcome/index.html.haml
= link_to t('posts.new'), new_post_path
= render partial: 'welcome/post', collection: @posts